"""
Email service for FlynnMed.

Sends clinical notes and urgent care alerts via SMTP.

Configure in .env:
  SMTP_HOST       e.g. smtp.gmail.com
  SMTP_PORT       e.g. 587 (TLS) or 465 (SSL)
  SMTP_USER       sender email address
  SMTP_PASSWORD   SMTP password or app-specific password
  EMAIL_FROM      optional display name, e.g. "FlynnMed <noreply@example.com>"
"""
from __future__ import annotations

import os
import smtplib
import uuid
from email import utils as email_utils
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Dict

from dotenv import load_dotenv

from backend.product_config import PRODUCT_NAME

load_dotenv()


def _smtp_config() -> tuple[str, int, str, str]:
    host = os.getenv("SMTP_HOST", "")
    port = int(os.getenv("SMTP_PORT", "587"))
    user = os.getenv("SMTP_USER", "")
    password = os.getenv("SMTP_PASSWORD", "")
    return host, port, user, password


def _send(to_address: str, subject: str, html: str, text: str) -> None:
    host, port, user, password = _smtp_config()
    if not host or not user or not password:
        raise ValueError(
            "Email is not configured. Add SMTP_HOST, SMTP_USER, SMTP_PASSWORD to your .env file "
            "and restart the server. For Gmail, use an App Password (not your regular password)."
        )
    if password == "your-16-char-app-password-here":
        raise ValueError(
            "Replace SMTP_PASSWORD in .env with a real Gmail App Password. "
            "Go to myaccount.google.com -> Security -> 2-Step Verification -> App passwords."
        )
    from_addr = os.getenv("EMAIL_FROM") or f"{PRODUCT_NAME} <{user}>"
    sender_domain = user.split("@")[-1] if "@" in user else "flynnmed.ai"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to_address
    msg["Reply-To"] = user
    # These headers are required for proper deliverability and spam avoidance
    msg["Message-ID"] = f"<{uuid.uuid4().hex}@{sender_domain}>"
    msg["Date"] = email_utils.formatdate(localtime=False)
    msg["X-Mailer"] = f"{PRODUCT_NAME.replace(' ', '')}/1.0"
    msg["MIME-Version"] = "1.0"
    msg.attach(MIMEText(text, "plain", "utf-8"))
    msg.attach(MIMEText(html, "html", "utf-8"))
    try:
        if port == 465:
            with smtplib.SMTP_SSL(host, port, timeout=15) as smtp:
                smtp.ehlo()
                smtp.login(user, password)
                smtp.sendmail(user, to_address, msg.as_string())
        else:
            with smtplib.SMTP(host, port, timeout=15) as smtp:
                smtp.ehlo()
                smtp.starttls()
                smtp.ehlo()
                smtp.login(user, password)
                smtp.sendmail(user, to_address, msg.as_string())
    except smtplib.SMTPRecipientsRefused as exc:
        details = "; ".join(f"{addr}: {err[1].decode()}" for addr, err in exc.recipients.items())
        raise ValueError(f"Recipient refused by mail server: {details}")
    except smtplib.SMTPAuthenticationError:
        raise ValueError(
            "Gmail rejected the login. Make sure you are using a Gmail App Password, "
            "not your regular Gmail password. "
            "Generate one at: myaccount.google.com -> Security -> App passwords."
        )
    except smtplib.SMTPException as exc:
        raise ValueError(f"SMTP error: {exc}")


def send_clinical_note_email(to_address: str, display_name: str, note: Dict) -> None:
    """Send a formatted SOAP note to the patient/clinician's email address."""
    created = note.get("created_at", "")[:16].replace("T", " ")
    subject = f"{PRODUCT_NAME} -- Clinical Note ({note.get('created_at', '')[:10]})"

    text = (
        f"{PRODUCT_NAME} -- Clinical Note\n"
        f"Generated: {created} UTC   Patient: {display_name}\n\n"
        f"SUBJECTIVE\n{note.get('subjective', '-')}\n\n"
        f"OBJECTIVE\n{note.get('objective', '-')}\n\n"
        f"ASSESSMENT\n{note.get('assessment', '-')}\n\n"
        f"PLAN\n{note.get('plan', '-')}\n\n"
        f"Urgency: {note.get('urgency_level', 'routine').title()}\n\n"
        "---\n"
        f"Generated by {PRODUCT_NAME} AI -- for informational purposes only.\n"
        "Always consult a qualified healthcare professional for medical decisions.\n"
    )

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
body{{font-family:Inter,system-ui,sans-serif;color:#122227;max-width:660px;margin:0 auto;padding:1.5rem;}}
h1{{color:#0f6674;font-size:1.35rem;margin:0 0 0.25rem;}}
.meta{{color:#627174;font-size:0.82rem;margin-bottom:1.5rem;}}
.section{{margin-bottom:1.25rem;border-left:3px solid #0f6674;padding-left:1rem;}}
.section h2{{font-size:0.7rem;text-transform:uppercase;letter-spacing:0.06em;color:#0f6674;margin:0 0 0.3rem;}}
.section p{{margin:0;line-height:1.65;white-space:pre-wrap;}}
.badge{{display:inline-block;padding:.3rem .7rem;border-radius:999px;font-size:.8rem;font-weight:700;}}
.routine{{background:#edf8f4;color:#2c7a57;}}
.elevated{{background:#fff8e5;color:#b88920;}}
.high,.urgent,.crisis{{background:#fff0ed;color:#b42318;}}
.footer{{font-size:.75rem;color:#627174;border-top:1px solid #d8e2df;margin-top:1.5rem;padding-top:1rem;}}
</style></head><body>
<h1>{PRODUCT_NAME} -- Clinical Note</h1>
<p class="meta">Generated: {created} UTC &nbsp;|&nbsp; Patient: {display_name}</p>
<div class="section"><h2>Subjective</h2><p>{note.get('subjective','-')}</p></div>
<div class="section"><h2>Objective</h2><p>{note.get('objective','-')}</p></div>
<div class="section"><h2>Assessment</h2><p>{note.get('assessment','-')}</p></div>
<div class="section"><h2>Plan</h2><p>{note.get('plan','-')}</p></div>
<p>Urgency: <span class="badge {note.get('urgency_level','routine')}">{note.get('urgency_level','routine').title()}</span></p>
<p class="footer">Generated by {PRODUCT_NAME} AI -- for informational purposes only. Always consult a qualified healthcare professional for medical decisions.</p>
</body></html>"""

    _send(to_address, subject, html, text)


def send_verification_email(to_address: str, display_name: str, code: str) -> None:
    """Send a 6-digit email verification code to a new account holder."""
    subject = f"{PRODUCT_NAME} - Verify your email address"

    text = (
        f"Hi {display_name},\n\n"
        f"Your {PRODUCT_NAME} verification code is: {code}\n\n"
        "Enter this code on the verification screen to activate your account.\n"
        "The code expires in 15 minutes.\n\n"
        f"If you did not create a {PRODUCT_NAME} account, ignore this email.\n"
    )

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
body{{font-family:Inter,system-ui,sans-serif;color:#122227;max-width:520px;margin:0 auto;padding:1.5rem;}}
h1{{color:#0f6674;font-size:1.2rem;margin:0 0 0.5rem;}}
.code-box{{background:#f0faf9;border:2px solid #0f6674;border-radius:12px;text-align:center;padding:1.5rem;margin:1.5rem 0;}}
.code{{font-size:2.8rem;font-weight:900;letter-spacing:0.25em;color:#0f6674;font-variant-numeric:tabular-nums;}}
.expiry{{font-size:0.82rem;color:#627174;margin-top:0.4rem;}}
.footer{{font-size:.75rem;color:#627174;border-top:1px solid #d8e2df;margin-top:1.5rem;padding-top:1rem;}}
</style></head><body>
<h1>Verify your {PRODUCT_NAME} account</h1>
<p>Hi {display_name}, enter this code on the verification screen:</p>
<div class="code-box">
  <div class="code">{code}</div>
  <div class="expiry">Expires in 15 minutes</div>
</div>
<p>If you did not create a {PRODUCT_NAME} account, you can safely ignore this email.</p>
<p class="footer">{PRODUCT_NAME} AI - secure health workspace</p>
</body></html>"""

    _send(to_address, subject, html, text)


def send_urgent_care_alert(
    to_address: str, display_name: str, reason: str, urgency_level: str
) -> None:
    """Send an urgent care alert email recommending the patient see a GP or seek emergency care."""
    level = urgency_level.lower()
    actions = {
        "high":   ("Please see your GP as soon as possible", "#d7674d"),
        "urgent": ("Please seek urgent medical care today",  "#b42318"),
        "crisis": ("Please call 999 / seek emergency help now", "#b42318"),
    }
    action, color = actions.get(level, ("Please speak to your GP", "#d7674d"))
    subject = f"{PRODUCT_NAME} -- {action}"

    text = (
        f"{PRODUCT_NAME} -- Health Alert\n\n"
        f"Hi {display_name},\n\n"
        f"Based on your recent {PRODUCT_NAME} consultation, we recommend:\n\n"
        f"  {action.upper()}\n\n"
        f"Reason: {reason}\n\n"
        "What to do:\n"
        "• Contact your GP and explain your symptoms are urgent\n"
        "• If you cannot reach your GP, call 111 (UK) or your local urgent care line\n"
        "• In an emergency, call 999 (UK) or your local emergency services\n\n"
        "---\n"
        f"{PRODUCT_NAME} AI -- always consult a qualified healthcare professional for medical decisions.\n"
    )

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
body{{font-family:Inter,system-ui,sans-serif;color:#122227;max-width:560px;margin:0 auto;padding:1.5rem;}}
h1{{color:#0f6674;font-size:1.2rem;}}
.box{{background:#fff0ed;border:2px solid {color};border-radius:10px;padding:1.2rem;margin:1rem 0;}}
.box h2{{color:{color};margin:0 0 .5rem;font-size:1.15rem;}}
.box p{{margin:0;line-height:1.55;}}
ul{{line-height:1.9;padding-left:1.2rem;}}
.footer{{font-size:.75rem;color:#627174;border-top:1px solid #d8e2df;margin-top:1.5rem;padding-top:1rem;}}
</style></head><body>
<h1>{PRODUCT_NAME} -- Health Alert</h1>
<p>Hi {display_name},</p>
<div class="box"><h2>{action}</h2><p>{reason}</p></div>
<p><strong>What to do:</strong></p>
<ul>
<li>Contact your GP and explain your symptoms are urgent</li>
<li>If you cannot reach your GP, call <strong>111</strong> (UK) or your local urgent care line</li>
<li>In an emergency, call <strong>999</strong> (UK) or your local emergency services</li>
</ul>
<p class="footer">{PRODUCT_NAME} AI -- always consult a qualified healthcare professional for medical decisions.</p>
</body></html>"""

    _send(to_address, subject, html, text)
